
version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: healthcare
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: mysql://user:password@db/healthcare

volumes:
  mysql_data:


